apiVersion: v1
kind: Service
metadata:
  name: sensor-nodeport
  namespace: default
spec:
    type: NodePort
    selector:
      app: sensor
    ports:
        - port: 5000
          targetPort: 5000
          nodePort: 30001
